@host = http://localhost
@port = 5128
@token = CfDJ8Pa8Aswr_RVOorw7a7SOD6RmcCYwJqzq-_Jmd5CaAuUGwO4T6A1IaX_levVd_1bzk2b5DqSpfEWmMRHtvEt2w-ZzBLFw48GdMbSXnmwdV6uModglj84Pm2TmxKUhlFsff0h00xnuS8lzRsjapTI5GIE6njPIafqyVE2lENJ4B-191HiwJyIGD84GzAHCixj7ov2l7_flNVceoenQPUdFcVW3Ayb--ZqiDcld2RZEUz6b93rS5dviAYP681Cn0R20qw1wkDgSsw2PH64jLUFILvihTx0z1-N_W1NpKvM930jY1GaQDt-wbQDhIjYU0aoWfKWdQEblJ9cVMPbdM9ZUGiHNPwhbmvykm2RvAWTwKDYh7z6ju6iIuBAO3zYKSmbSs0BgMUpm9RDgDuB1f6m6ryBy9rWd_HY6SVHJWSn3y3J00gogMQXm_P1dtqK7YJeGAX3LEammS8gzyBRciVKL0m8d2qwb9kNZ1GyoIRhNRDrvPYqP8FINKyCnNm0HmvumknudLp4-fpvuSVe5OQxdzj988OAAnHW2_iboPsWPVw0pOUIm3yznrxLcwiOFC1QmTFXMQYpFc6m2_U6Gvyz-aivt3cRSrhFBgelifLSWUM-9LSOevJ6_U6RkJbLLA_9KZg4NnKdN3cY3HMxb_etnMO7IunZVk3eGWaKAp13BcDP6XPlrzrZW080sVnom4Z2VgyvHD8KGy_9mjqCqOjfS7z2oyEcoWeTBFJQEaEm_MXoMWl9mtW0koFairbA98jZ2Y4uqfmzI0jvqQ9KMLB4D6CEpSLZpof_lHQU70sRjMuvF


@Restaurants.API_HostAddress = https://localhost:7089

GET {{Restaurants.API_HostAddress}}/api/weatherforecast/example
Accept: application/json
ProjectUrl: {{$projectUrl}}
Guid: {{$guid}}
LocalDate: {{$datetime iso8601}}
Random-Int: {{$randomInt}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization:Bearer {{token}}


###

GET {{Restaurants.API_HostAddress}}/api/restaurants/2

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization : Bearer {{token}}
Content-Type: application/json
{
  "Name": "Ayam Geprek With New User@mail.com",
  "Description": "Traditional Store",
  "Category": "Fast Food",
  "HasDelivery": true,
  "ContactEmail": null,
  "ContactPhone": null,
  "City": "London",
  "Street": "Boots 193",
  "PostalCode": "11-100"
}

###

@id=0
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/2

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name":"Update Warung No 222",
  "Description":"Some Description",
  "HasDeliver": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes
Content-Type: application/json

{
   "Name":"Super Panas 2",
  "Description":"Ayam 1 Nasi 1 Dan 1 Minuman",
  "Price":50000,
  "KiloCalories":100
}

###

@restaurantId=1
GET {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes

###

@dishId=3
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{dishId}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes/

###


POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
  "email":"User@mail.com",
  "password":"Password1!"
}


###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email":"Owner@mail.com",
  "password":"Password1!"
}