@host = http://localhost
@port = 5128
@token = CfDJ8Pa8Aswr_RVOorw7a7SOD6QzeWTvFU9eL0Ucxvblc5U9BUZw5laZXRd6R2oXkQAUpRUotIjGqEymQPOzeq_kCZCfZ5Meov68LoYMIgmY-TqC28REpehAFse0AJGAZMzmRlXtBQnICIClcfX_XEyIDt93geVpamUkITIbdC7NcPun7SEuOviK1JKK_coTtXMJ6JplMJAFmEHtb2IAMRrEOO2zBBaaqodqS5HKb2dFEKgJnjH-5Tp3rueThtqBlxqVCyaVPMLf-CFyN2QetIv2HM4G-CDUYzxWUWDg-seIeAoVIOJg-yzUDakAJB24ooI3cF8zri3E4XwLMry83GPJrZDtRbh_Q7GSXqzpT-fvB9BqbS7xRWXaJy5AYu8Y_IjOc8ycLJLf7rxgVRMl2xazoTNBhz2QXytCxGp6yyyDPbUDbCvqJJUJYGF9Y8MRV08ashVIdaybz-O4FjFiVktyZbydHEjvt7T8FNtCb4eY0iMN2h4tV1EMDlAFz4W1p8g24jY2ExF60yzFz8wzKV7SHq_Y1Bj5sroiVd9wo_vv97ap61In6I_V0BHo4MfvcZOWGRsNvq4JqUAiGy9ziaUAoI0Ld12vyBlJiYqW9m7p2KksaQgSicgT_pdzGat0t1IsC8LYb_Azaua-qlN7JV3Q04JRivCe1yoozdM1V8M5HVD8IPc3-1yeil4D_ebJ-T3N5iEryGRbiv6IN1UV8KJZ7AsAK_pZ3lXS4yURqUJvk_2jTSp_1DWteMa3JvqlcikCCQKiZuPL51nQqKGigqHT37oPDbikMzvjWDUSebjRwGI9


@Restaurants.API_HostAddress = https://localhost:7089

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email":"owner@mail.com",
  "password":"Password1!"
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants?SearchParam=ayam&pageSize=10&pageNumber=1&sortBy=Name&sortDirection=Descending
Authorization:Bearer {{token}}


###

GET {{Restaurants.API_HostAddress}}/api/restaurants/14

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization : Bearer {{token}}
Content-Type: application/json
{
  "Name": "new owner2 restaurant 2",
  "Description": "Traditional Store",
  "Category": "Fast Food",
  "HasDelivery": true,
  "ContactEmail": null,
  "ContactPhone": null,
  "City": "London",
  "Street": "Boots 193",
  "PostalCode": "11-100"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/14
Content-Type: application/json
Authorization: Bearer {{token}}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name":"Update Warung No 222",
  "Description":"Some Description",
  "HasDeliver": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes
Content-Type: application/json

{
   "Name":"Super Panas 2",
  "Description":"Ayam 1 Nasi 1 Dan 1 Minuman",
  "Price":50000,
  "KiloCalories":100
}

###

@restaurantId=1
GET {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes

###

@dishId=3
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{dishId}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes/

###


POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
  "email":"admin@mail.com",
  "password":"Password1!"
}



###

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "UserEmail":"owner2@mail.com",
  "RoleName":"Owner"
}

###

@id=11
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###
